name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        region:
          - USA
          - TWN
          - PAL
          - KOR
          - JAP

    steps:
    - uses: actions/checkout@v2
    - shell: pwsh
      run: |
          Invoke-WebRequest -Uri "https://github.com/Lord-Giganticus/CodeWarriorDemangler/releases/latest/download/CWD.jar" -OutFile CWD.jar
          Invoke-WebRequest -Uri "https://github.com/Lord-Giganticus/Syati/raw/main/symbols/${{matrix.region}}.txt" -OutFile ${{matrix.region}}.txt
    - shell: cmd
      run: java -jar cwd.jar ${{matrix.region}}.txt > demangled_${{matrix.region}}.txt
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: ${{matrix.region}}
        path: demangled_${{matrix.region}}.txt
