name: Python application

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        region:
          - USA
          - TWN
          - PAL
          - KOR
          - JAP

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - shell: pwsh
      run: |
          Invoke-WebRequest -Uri "https://github.com/RealTheSunCat/CodeWarriorDemangler/releases/latest/download/CWD.jar" -OutFile CWD.jar
          Invoke-WebRequest -Uri "https://github.com/Lord-Giganticus/Syati/raw/main/symbols/${{matrix.region}}.txt" -OutFile ${{matrix.region}}.txt
    - shell: cmd
      run: |
          for /F "tokens=*" %%A in (${{matrix.region}}.txt) do java -jar CWD.jar "%%A" >> ${{matrix.region}}_demangled.txt
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: ${{matrix.region}}
        path: ${{matrix.region}}.txt
